In [1]:
import numpy as np

In [8]:
# ndarray 생벙 방법 1.
arr1 = np.array([10, 20, 30]) # 1차원
print(arr1)
print(type(arr1))
print()
arr2 = np.array([[10, 20, 30], [100, 200, 300]]) # 2차원
print(arr2)
print(type(arr2))

[10 20 30]
<class 'numpy.ndarray'>

[[ 10  20  30]
 [100 200 300]]
<class 'numpy.ndarray'>


In [12]:
# ndarray 생성 방법 2.
arr3 = np.arange(1, 11, 1) # 1 <= x < 11, 1씩 증가
print(arr3)
print()
arr4 = np.arange(1, 11, 2) # 1 <= x < 11, 2씩 증가
print(arr4)

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [17]:
# ndarray 생성 방법 3
arr5 = np.random.randint(1, 11, size=5) # 1 <= x < 11, 임의의 정수 5개 
print(arr5)
print(type(arr5))
print()
arr6 = np.random.randint(1, 11, size=(3, 2)) # 1 <= x < 11, 임의의 정수 3행 2열 
print(arr6)
print(type(arr6))

[7 5 5 8 7]
<class 'numpy.ndarray'>

[[ 3  3]
 [10  2]
 [ 6  7]]
<class 'numpy.ndarray'>


In [42]:
arr7 = np.random.rand(2) # 0 ~ 1 임의의 실수 2개
print(arr7)
print()
arr8 = np.random.rand(2, 3) # 0 ~ 1 임의의 실수 2행 3열
print(arr8)

[0.20740392 0.6264415 ]
<class 'numpy.ndarray'>

[[0.45948166 0.60825737 0.55567239]
 [0.45449324 0.50420461 0.36897497]]
<class 'numpy.ndarray'>


In [48]:
arr8 = np.random.randn(10000) # 표준정규분포(평균 0, 표준편차 1), 개수가 많을수록 표준정규분포에 가까워진다.
print(arr8)

[-1.01961541 -1.66413366 -0.63360088 ...  0.02382813 -0.09508011
  0.99450635]
<class 'numpy.ndarray'>


In [52]:
arr9 = np.random.choice([1, 2, 3, 4, 5], 3) # 임의로 3개 복원 추출
print(arr9)
print()
arr10 = np.random.choice(np.arange(1, 6), 5, replace=False) # 임의로 5개 비복원 추출
print(arr10)

[4 5 3]

[3 2 5 4 1]


In [61]:
arr11 = np.arange(1, 11)
np.random.shuffle(arr11) # 데이터 무작위로 섞기
print(arr11)

[ 8  7  2 10  4  1  6  3  9  5]


In [67]:
# ndarray 생성 방법 3. 
arr12 = np.int32([1, 2, 3, 4, 5]) # 데이터 하나가 4byte, 즉 32bit
print(arr12, arr12.dtype, '\n')
arr13 = np.float32([1, 2, 3, 4, 5])
print(arr13, arr13.dtype, '\n')
arr14 = np.array([1, 2, 3, 4, 5], dtype='<U1')
print(arr14, arr14.dtype)

[1 2 3 4 5] int32 

[1. 2. 3. 4. 5.] float32 

['1' '2' '3' '4' '5'] <U1


In [73]:
# ndarray 생성 방법 4.
print(np.ones((3, 3)), '\n') # 데이터가 모두 1
print(np.zeros((3, 3)), '\n') # 데이터가 모두 0
print(np.eye(3), '\n') # sparse 매트릭스(희소 행렬), one hote encoding

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [74]:
print(np.linspace(1, 10, 50)) # 1 <= x <=10, 50개 동일한 간격으로 

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])