In [1]:
import numpy as np

### 속성

In [3]:
arr = np.array([11, 22, 33, 44, 55])
print(arr)

[11 22 33 44 55]


In [4]:
# 데이터 타입
print(arr.dtype)

int64


In [5]:
# ndarray 크기
print(arr.size)

5


In [6]:
# ndarray 형태 
print(arr.shape)

(5,)


In [7]:
# 차원 
print(arr.ndim)

1


In [11]:
# 형 변환(nxm -> mxn)
arr1 = np.array([[11, 22], [33, 44], [55, 66]])
print(arr1, '\n')
print(arr1.T)

[[11 22]
 [33 44]
 [55 66]] 

[[11 33 55]
 [22 44 66]]


### 변환함수

In [19]:
# 데이터 타입 변환
print(arr.dtype, '\n')
arr2 = arr.astype('float64')
arr3 = arr.astype(np.float64)
print(arr2.dtype, '\n')
print(arr3.dtype)


int64 

float64 

float64


In [22]:
# 형 변환
print(arr1, arr1.shape, '\n')
arr4 = arr1.reshape(2, -1) # -1: 자동 계산
print(arr4, arr4.shape)

[[11 22]
 [33 44]
 [55 66]] (3, 2) 

[[11 22 33]
 [44 55 66]] (2, 3)
