In [1]:
import numpy as np

### 인덱싱

In [3]:
arr = np.array([11, 22, 33, 44, 55])
print(arr)

[11 22 33 44 55]


In [11]:
# 데이터 하나 선택
# 인덱스 번호 0부터 시작
# 끝에서 -1부터 시작
print(arr[0])
print(arr[-1])

11
55


In [10]:
# 데이터 복수개 선택
print(arr[[0, -1]])

[11 55]


In [17]:
# 불린 인덱싱(boolean indexing)
# True에 해당하는 데이터 출력
# 데이터 개수와 불린 개수가 같아야 한다
print(arr[[True, True, False, False, True]])

[11 22 55]


### 슬라이싱

In [26]:
# [시작 : 끝 : 증가치]
print(arr[1:4]) # 1 <= index < 4, 증가치 생략시 1씩 증가
print(arr[1:4:2]) # 1 <= index < 4, 2씩 증가
print(arr[:]) # 모든 데이터 선택
print(arr[:4]) # 시작 생략시 0
print(arr[1:]) # 끝 생략시 마지막 데이터까지
print(arr[1:-1])
print(arr[::-1]) # 역순으로 출력

[22 33 44]
[22 44]
[11 22 33 44 55]
[11 22 33 44]
[22 33 44 55]
[22 33 44]
[55 44 33 22 11]


### 연산(산술, 관계, 논리)
- element wise(요소별 연산)

1. 산술 연산 

In [28]:
arr = np.array([11, 22, 33, 44, 55])
print(arr)

[11 22 33 44 55]


In [31]:
print(arr + 2)
print(arr -2)
print(arr * 2)
print(arr /2)

[13 24 35 46 57]
[ 9 20 31 42 53]
[ 22  44  66  88 110]
[ 5.5 11.  16.5 22.  27.5]


In [32]:
arr1 = np.array([1, 2, 3, 4, 5])
print(arr + arr1)

[12 24 36 48 60]


2. 관계 연산
- and: &
- or: |
- not: ~

In [33]:
print(arr > 30) # 참이면 True, 거짓이면 False 반환

[False False  True  True  True]


In [34]:
print(arr[arr > 30]) # boolean indexing

[33 44 55]


3. 논리 연산

In [39]:
arr

array([11, 22, 33, 44, 55])

In [46]:
print(arr[(arr > 20) & (arr < 50)]) # and
print(arr[(arr == 11)|(arr == 55)]) # or
print(arr[~((arr > 20) & (arr < 50))]) # not, and

[22 33 44]
[11 55]
[11 55]


4. 조건 연산

In [48]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [50]:
conList = [arr>40, arr>20, arr>0]
choiceList = ['A', 'B', 'C']
print(np.select(conList, choiceList))

['C' 'C' 'B' 'B' 'A']
