In [1]:
import numpy as np

### 추가

In [2]:
arr = np.array([11, 22, 33, 44, 55])
print(arr)

[11 22 33 44 55]


In [3]:
a = np.array([100, 200])
arr1 = np.append(arr, a) # arr 끝에 a 추가
print(arr1)

[ 11  22  33  44  55 100 200]


In [4]:
b = np.array([300, 400])
arr2 = np.insert(arr, 1, b) # arr 인덱스 번호 1에 b 삽입
print(arr2)

[ 11 300 400  22  33  44  55]


###  수정

In [5]:
# 데이터 하나 수정
arr[0] = 1000
print(arr)

[1000   22   33   44   55]


In [6]:
# 복수개 데이터 수정
arr[[0,1]] = 2000, 1000
print(arr)

[2000 1000   33   44   55]


In [7]:
# 슬라이싱으로 데이터 수정
arr[:3] = 1, 2, 3
print(arr)

arr[:3] = arr[:3] + 2
print(arr)

[ 1  2  3 44 55]
[ 3  4  5 44 55]


In [8]:
# 10보다 큰 데이터 기존 값 + 100으로 수정 
arr[arr > 10] = arr[arr > 10] + 100
print(arr)

[  3   4   5 144 155]


### 삭제

In [12]:
print(np.delete(arr, (0,1))) # arr의 0, 1번 인덱스 값 삭제

[  5 144 155]


In [16]:
print(np.where(arr < 10)) # 조건 만족하는 값의 인덱스 번호 반환
print(np.where(arr < 10, '참', '거짓')) # 조건 만족하는 값 '참', 만족 안하는 값 '거짓'으로 반환

(array([0, 1, 2]),)
['참' '참' '참' '거짓' '거짓']


In [18]:
print(np.delete(arr, np.where(arr < 10))) # arr에서 10보다 작은 값 삭제

[144 155]


### 정렬

In [30]:
# 오름차순 정렬
arr = np.array([5, 7, 0, 2, 4])
print(np.sort(arr))
# 내림차순 정렬
print(np.sort(arr)[::-1]) 

[0 2 4 5 7]
[7 5 4 2 0]


In [31]:
# 오름차순 정렬된 데이터들의 인덱스
print(np.argsort(arr))
# 내림차순 정렬된 데이터들의 인덱스
print(np.argsort(-arr))

[2 3 4 0 1]
[1 0 4 3 2]
