In [1]:
import numpy as np

In [3]:
data = np.array([[1, 2, 3], [4, 5, 6], [9, 8, 7], [6, 3, 4]])
print(data)

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [6 3 4]]


### 인덱싱, 슬라이싱

In [19]:
print(data[0, 0], '\n') # 행, 열
print(data[:,0], '\n') # 전체 행에서 0번째 열(형태가 바뀐다)
print(data[:,[0]], '\n') # 전체 행에서 0번째 열(형태 유지)
print(data[[0,2,3]], '\n') # 복수개 행 
print(data[:, [0,2]], '\n') # 복수개 열
print(data[:,:-1]) # 마지막 열 제외

1 

[1 4 9 6] 

[[1]
 [4]
 [9]
 [6]] 

[[1 2 3]
 [9 8 7]
 [6 3 4]] 

[[1 3]
 [4 6]
 [9 7]
 [6 4]] 

[[1 2]
 [4 5]
 [9 8]
 [6 3]]


In [22]:
# boolean indexing
# 행의 개수와 같아야 한다.
print(len(data)) # 행의 개수
print(data[[True, True, False, True]]) # True에 해당하는 행 출력

4
[[1 2 3]
 [4 5 6]
 [6 3 4]]


### 연산

In [24]:
print(data)

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [6 3 4]]


In [23]:
print(data + 2)

[[ 3  4  5]
 [ 6  7  8]
 [11 10  9]
 [ 8  5  6]]


In [29]:
print(data[data > 5]) # 1차원 반환
print(data[data[:, 0] > 5]) # column별 조건 주고 조건을 만족하는 행 출력

[6 9 8 7 6]
[[9 8 7]
 [6 3 4]]


### 추가, 수정, 삭제, 검색, 정렬

In [30]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[5, 6, 7], [7, 8, 6]])

In [34]:
print(arr1, arr2, arr3, sep='\n\n')

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[5 6 7]
 [7 8 6]]


In [40]:
print(np.append(arr1, arr2), '\n') # 1차원 반환
print(np.append(arr1, arr2, axis=0), '\n') # row 추가, column 개수 같아야 한다.
print(np.append(arr1, arr2, axis=1)) # column 추가, row 개수 같아야 한다.

[1 2 3 4 5 6 7 8] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


In [43]:
print(np.hstack((arr1, arr2)), '\n') # 수평으로 추가(column 추가)
print(np.vstack((arr1, arr2))) # 수직으로 추가 row 추가

[[1 2 5 6]
 [3 4 7 8]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
print(data, '\n')
print(np.delete(data, (0, 2)), '\n') # 1차원(벡터) 해석, 해당 인덱스 데이터 삭제
print(np.delete(data, (0, 2), axis=0), '\n') # 0, 2번째 row 삭제
print(np.delete(data, (0, 2), axis=1)) # 0, 2번째 column 삭제

[[1 2 3]
 [4 5 6]
 [9 8 7]
 [6 3 4]] 

[2 4 5 6 9 8 7 6 3 4] 

[[4 5 6]
 [6 3 4]] 

[[2]
 [5]
 [8]
 [3]]


In [60]:
print(np.sort(data, axis=None), '\n') # 벡터 정렬
print(np.sort(data), '\n') # row별 정렬
print(np.sort(data, axis=0)) # column별 정렬

[1 2 3 3 4 4 5 6 6 7 8 9] 

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [3 4 6]] 

[[1 2 3]
 [4 3 4]
 [6 5 6]
 [9 8 7]]


### 통계

In [64]:
print(np.sum(data), '\n') # 총합
print(np.sum(data, axis=0), '\n') # column별 합
print(np.sum(data, axis=1)) # row별 합

58 

[20 18 20] 

[ 6 15 24 13]
